export const fetchOrder ={type:'FETCH_ORDER_SUCCESS'};
export const fetchTableAvailable ={type:'FETCH_TABLE_AVAILABLE'};
export const fetchFoodMenu ={type:'FETCH_DATA_MENU'};
export const PICHandler ={type:'HANDLE_PIC_CUSTOMER'};
export const customerQuantityHandler ={type:'HANDLE_MANY_CUSTOMERS'};
export const tableIdHandler ={type:'HANDLE_ID_TABLE'};
export const addOrderMenu ={type:'ADD_ORDER_MENU'};
export const foodIdHandler ={type:'HANDLE_FOOD_ID'};
export const foodQuantityHandler ={type:'HANDLE_FOOD_QUANTITY'};
export const resetStateForm = {type: 'RESET_STATE_FORM'}
export const resetState = {type: 'RESET_STATE'}
